apiVersion: backstage.io/v10.0.0
kind: Component
metadata:
  name: shuffle-api-1
  description: Shuffle API 1
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: audio-playback
